### ISSUE TITLE
Stuck on compiling sketch? 

### ISSUE THREAD

**Issue by valkircrypto** [madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library#12]
When I try to compile the fileplayer example, it just stay at compiling sketch?
Any idea why?

**Comment by mpflaga** [comment]
Not really. It compiles in the latest IDE. I the IDEs preference out can turn on verbose. That may provide some insight.

**Comment by mpflaga** [comment]
Closing assuming the issue was self resolved.
