### ISSUE TITLE
mp3 shield and laptop as speaker

### ISSUE THREAD

**Issue by sonjaroth** [madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library#15]
Hi! 
I set up the MP3 Shield and it all worked perfectly - I was triggering tracks by connecting different  wires with ground - and was able to listen to the music through my headphones - then I decided to let connect it with another project - and I need a laptop to play the music now. So I soldered SJ3, SJ4 and SJ5 in order to have LINE out - now the music comes as suggested more quiet through the headphones - but though the laptop (mac os x 10.7.5) I can't hear any music. When i change the set up of the mac to: Sound Input - Output - I can see the movement of the music playing --- 

how can i make it be heard and played through my laptop speakers?? 

thanks so much for any help!

**Comment by mpflaga** [comment]
unfortunately I am not a MAC expert nor do I have one of the newest versions of shields with the jumpers. looking at the schematic I see if jumper-ed correctly they insert the needed AC coupling. Make sure only two not three pads are solder jumped. You could try shorting out the 470ohms R21,22,and or removing the 10K R15,16. But I doubt that will change things.

I wonder if it is more of an issue with the MAC's mixer, not sending the input to the PC's output speakers. That gets me sometimes on other PC's.
