### ISSUE TITLE
No working on Leonardo!

### ISSUE THREAD

**Issue by GabeHC** [madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library#16]
Stuck at SD initialization process. same code works on Uno! 
 I think it it SdFat library problem. but don't know how to fix it!

**Comment by mpflaga** [comment]
Support Documentation can be found at the below github page for this project http://mpflaga.github.com/Sparkfun-MP3-Player-Shield-Arduino-Library/
Please refer to the Trouble Shooting Section.

Additional support can be found at http://www.billporter.info/forum/forum/sparkfun-mp3-shield-support-forum/
