### ISSUE TITLE
FilePlayer Error 2 when playing track

### ISSUE THREAD

**Issue by DominicHDH** [madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library#18]
Hello,

I'm having some trouble with the fileplayer example code. I used the exact same example code from the resources, i've labeled all of my tracks "track001.mp3, etc...", but I keep getting error 2 when playing track when I try to play a track. Thanks for the help!

**Comment by stefandz** [comment]
Quick check - what if you name them TRACK001.MP3 (i.e. all uppercase)?

**Comment by mpflaga** [comment]
I recommend reading the following support page.
http://mpflaga.github.io/Sparkfun-MP3-Player-Shield-Arduino-Library/#Troubleshooting.

**Comment by mpflaga** [comment]
Closing assuming the issue was self resolved.
