### ISSUE TITLE
.wav playing on lilypadMP3 with SFEMP3 library

### ISSUE THREAD

**Issue by domleray** [madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library#23]
Hi,
I use a sketch using SFEMP3 library playing randomly MP3 files from a lilypadMP3 SD card.
What is the magical way to make it read .wav files .... ?
Thanks for your help.
Dom

**Comment by mpflaga** [comment]
It has been a while. But I recall there is nothing magical. The file contents are streamed to the VSP1052 where it auto detects the headers of the file and determines the format. So you should simple just call the filename. There is a demo example that lets you select filenames. 

Take a look at https://gist.github.com/mpflaga/ there are a lot of examples that I have created in responses to questions.

**Comment by domleray** [comment]
Thank you for your answer.
I tried FileNamePlayer.ino and  MP3random.ino.
They perfectly read MP3 files but return an error when playing Wav files :
Error code: 2 when trying to play track 
I made .wav files using audacity... sample rate 44100khz, 16bits....
Any idea? 
Thanks




dominique.leray

From: Michael P. Flaga
Date: 2020-06-06 17:22
To: madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library
CC: domleray; Author
Subject: Re: [madsci1016/Sparkfun-MP3-Player-Shield-Arduino-Library] .wav playing on lilypadMP3 with SFEMP3 library (#23)
It has been a while. But I recall there is nothing magical. The file contents are streamed to the VSP1052 where it auto detects the headers of the file and determines the format. So you should simple just call the filename. There is a demo example that lets you select filenames.
Take a look at https://gist.github.com/mpflaga/ there are a lot of examples that I have created in responses to questions.
